import StyledProvider from '@/app/StyledProvider'
import TestNav from '@/components/navigate/TestNav'
import { Metadata } from 'next'
import localFont from 'next/font/local'
import { Suspense } from 'react'
import StoreProvider from './StoreProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: '../assets/font/NotoSans-VariableFont_wdth,wght.ttf',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <StoreProvider>
          <StyledProvider>
            <Suspense>
              <TestNav />
              {children}
            </Suspense>
          </StyledProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
