import StyledProvider from '@/app/StyledProvider'
import { Metadata } from 'next'
import localFont from 'next/font/local'
import StoreProvider from './StoreProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: '../assets/font/NotoSans-VariableFont_wdth,wght.ttf',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={myFont.className}>
      <body>
        <StoreProvider>
          <StyledProvider>{children}</StyledProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
